name: First_Workflow_tanu_dev

on:

  workflow_dispatch:   #runs the workflow manually
env : 
  workflow_var : workflow_val

jobs:
  basic-demo_1:
    runs-on: ubuntu-latest

    env :
      job_var : job_val_tan

    steps:
    
      - name: Say Hello multipale step run
        env :
          step_var : step_val
        run: |
          echo "Hello from Tanuja Technologies step_var value = $step_var and job_var = $job_var and workflow_var = $workflow_var" 
          date
          uname -a

      - name: List current directory
        run: ls -ltr

      - name: Print current user
        run: whoami

      - name: Print date and time
        run: date
      - name: print hostname
        run: hostname
